apiVersion: v1
kind: Service
metadata:
  name: demo-k8s-service
spec:
  selector:
    app: demo-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer   # hoặc ClusterIP nếu dùng Ingress